providers:
  file:
    directory: "/etc/traefik/dconf"
    watch: true
api:
#  insecure: true
  dashboard: true
entryPoints:
  web:
    address: ":80"
    transport:
      lifeCycle:
        graceTimeOut: "1"
  websecure:
    address: ":443"
    transport:
      lifeCycle:
        graceTimeOut: "1"
    # habilitar isso se todas as rotas forem usar ceriticados
    # http:
      # tls:
        # certResolver: letsencrypt
#log:
#  level: DEBUG
#  format: json

# alterar mod do arquivo acme.json ou o traefik nao vai funcionar
# tem que anterar dentro da imagem docker
# docker exec -it traefik ash
# chmod 600 acme.json
certificatesResolvers:
  letsencrypt:
    acme:
      email: diegofontanabr@gmail.com
      storage: /etc/traefik/acme/certificates.json
      caServer: https://acme-v02.api.letsencrypt.org/directory
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      httpChallenge:
        entryPoint: web
      tlsChallenge: {}
